{{- if or (eq .Values.serviceAccount.create true) (eq .Values.datadogAgent.enabled true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrator.serviceAccountName" . }}
  labels:
    {{- include "orchestrator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
